### ISSUE TITLE
validator: missing kafka output

### ISSUE THREAD

**Issue by nicolasparada** [calyptia/go-fluentbit-config#49]
Missing `kafka` output from schema https://docs.fluentbit.io/manual/pipeline/outputs/kafka

**Comment by patrick-stephens** [comment]
See https://github.com/calyptia/core-fluent-bit/pull/17. Be good to resolve but probably in upstream - we would not be enabling experimental inputs for LTS.

**Comment by pwhelan** [comment]
We don't need the input support... sorry about that.

@nicolasparada are we using this file for the schema? It seems the kafka output stuff is right there.

https://github.com/calyptia/core-images-index/blob/main/schemas/23.1.2/core-fluent-bit-pretty.json#L5914

**Comment by nicolasparada** [comment]
Great, then we just need to update this repo and use the schema from the index then 👍
